### PR TITLE
Add new test test_process_pool_repeated_stopping to show #58.

### PR DESCRIPTION
**Pull request by marxin**
Make pytest run with -s in order to print output.

### CODE REVIEW

**Comment by marxin** [comment]
I can't trigger Travis here, but I see:
```
pytest test_process_pool_fork.py::TestProcessPool::test_process_pool_repeated_stopping
Test session starts (platform: linux, Python 3.8.2, pytest 4.6.9, pytest-sugar 0.9.2)
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/marxin/Programming/pebble
plugins: forked-1.1.3, benchmark-3.2.3, xdist-1.31.0, flake8-1.0.4, aspectlib-1.4.2, sugar-0.9.2, cov-2.8.1
collecting ... 
 test/test_process_pool_fork.py ✓                                                                                                                                                                                                                                100% ██████████

Results (3.14s):
       1 passed
```

```
pytest test_process_pool_fork.py::TestProcessPool::test_process_pool_repeated_stopping -s
Test session starts (platform: linux, Python 3.8.2, pytest 4.6.9, pytest-sugar 0.9.2)
benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/marxin/Programming/pebble
plugins: forked-1.1.3, benchmark-3.2.3, xdist-1.31.0, flake8-1.0.4, aspectlib-1.4.2, sugar-0.9.2, cov-2.8.1
collecting ... Exception in thread Thread-3:
...
Exception in thread Thread-81:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/pebble/pool/process.py", line 178, in message_manager_loop
    pool_manager.process_next_message(SLEEP_UNIT)
  File "/usr/lib/python3.8/site-packages/pebble/pool/process.py", line 210, in process_next_message
    message = self.worker_manager.receive(timeout)
  File "/usr/lib/python3.8/site-packages/pebble/pool/process.py", line 342, in receive
    return self.pool_channel.recv()
  File "/usr/lib/python3.8/site-packages/pebble/pool/channel.py", line 63, in recv
    return self.reader.recv()
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 421, in _recv_bytes
    return self._recv(size)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
TypeError: an integer is required (got type NoneType)

 test/test_process_pool_fork.py ✓                                                                                                                                                                                                                                100% ██████████

Results (3.14s):
       1 passed
```

**Comment by noxdafox** [comment]
This test is invalid for a couple of reasons.

Firstly, it tries to reproduce a concurrency issue which in itself it's very hard to reliably test. It tries to ensure the problem to manifest itself by repeating something an arbitrary amount of times. This would lead to tests failing intermittently which is very hard to investigate. On my environment, the above test does not manifest the problem 1 time out of 3.

Secondly, the test does not actually assert anything. Therefore, the test suite cannot assess whether the test is passing or not. In other words, the above test always passes hiding the fact it's failing. 

You cannot test issue #58 properly as the pool already does a good job handling the core issue. The only effect of issue #58 is a spurious error message which has been easily silenced.

**Comment by marxin** [comment]
I understand the reason why you didn't merge the pull request.

**Comment by noxdafox** [comment]
I encounter few other instances of issue #58 in the past and I was not able myself to write proper tests for that. 

What you observe is a noisy handling of an issue occurring when terminating the pool.

**Pull request closed without merging**
